name: 자동 로또 구매결과 pw (SH)

on:
  schedule:
    # 매주 월요일 오전 11시에 실행 (UTC+9, 한국 시간)
    # cron은 UTC 시간을 기준으로 하므로 한국 시간 오전 11시는 UTC 02:00
    - cron: '0 2 * * 1'
  workflow_dispatch: # 수동 실행 가능하도록 설정

jobs:
  buy-lotto:
    name: 자동 로또 구매 실행
    runs-on: ubuntu-latest

    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v3

      - name: Node.js 설정
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: pnpm 설치
        uses: pnpm/action-setup@v2
        with:
          version: 10
          run_install: false

      - name: pnpm 캐시 활성화
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: 의존성 설치
        run: pnpm install

      - name: Playwright 브라우저 설치
        run: npx playwright install --with-deps chromium

      - name: Playwright 환경 확인
        run: npx playwright install-deps chromium && ls -la /home/runner/.cache/ms-playwright/

      - name: 로또 구매 실행
        env:
          LOTTO_USER_ID: ${{ secrets.LOTTO_USER_ID_SH }}
          LOTTO_USER_PW: ${{ secrets.LOTTO_USER_PW_SH }}
          LOTTO_COUNT: ${{ secrets.LOTTO_COUNT || 5 }}
          SLACK_API_URL: ${{ secrets.SLACK_API_URL }}
          CLIENT_EMAIL: ${{ secrets.CLIENT_EMAIL }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID_SH }}
          PLAYWRIGHT_BROWSERS_PATH: /home/runner/.cache/ms-playwright
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 3
          max_attempts: 1
          retry_on: error
          command: pnpm lotto:pw-re:headless-debug
